(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(global-linum-mode t)
(electric-pair-mode t)
(load-theme 'leuven)
(set-default-font "Courier 10 Pitch-12")
(setq-default c-basic-offset 4)
(setq-default c-default-style "k&r")
(setq-default cursor-type 'bar)
